services:
  blog_db:
    image: postgres:17-alpine
    container_name: blog_db
    environment:
      POSTGRES_USER: blogadmin
      POSTGRES_PASSWORD: skyconet
      POSTGRES_DB: blog_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: blog_redis
    ports:
      - "6379:6379"

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env
    environment:
      NODE_ENV: development

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./frontend/.env
    environment:
      NODE_ENV: development
    depends_on:
      - backend
volumes:
  postgres_data:

networks:
  default:
    driver: bridge